---

- name: "LDAPSYNC: Package: Install components for sync script"
  ansible.builtin.package:
    pkg:
      - "python3-ldap3"
      - "python3-cs"
      - "python3-click"
    state: present

- name: "LDAPSYNC: Install configuration"
  template:
    src: cloudstack-ldapsync.conf
    dest: /etc/cloudstack/ldapsync.conf
    owner: root
    mode: 0600

- name: "LDAPSYNC: Install sync script"
  copy:
    src: cloudstack-ldapsync.py
    dest: /usr/local/bin/cloudstack-ldapsync.py
    owner: root
    mode: 0700

- name: "LDAPSYNC: Perform sync"
  shell: /usr/local/bin/cloudstack-ldapsync.py
  register: sync
  changed_when: sync.stdout_lines | count > 1
  run_once: true

- name: "LDAPSYNC: Add cron task"
  template:
    src: cloudstack-ldapsync.cron
    dest: /etc/cron.d/cloudstack-ldapsync
    owner: root
    mode: 0644
