---
- name: "APT: see if we have a keyring"
  ansible.builtin.stat:
    path: /etc/apt/trusted.gpg.d/cloudstack.asc
  register: keyring_exists

- name: "APT: fetch keyring"
  ansible.builtin.get_url:
    url: https://download.cloudstack.org/release.asc
    dest: /etc/apt/trusted.gpg.d/cloudstack.asc
    mode: "644"
  when: not keyring_exists.stat.exists
  register: keyring

- name: "APT: Import Key"
  ansible.builtin.command: "apt-key add /etc/apt/trusted.gpg.d/cloudstack.asc"
  when: keyring.changed

- name: "APT: Install cloudstack repository"
  ansible.builtin.template:
    src: cloudstack.sources.j2
    dest: /etc/apt/sources.list.d/cloudstack.sources
    owner: root
    mode: "644"
  register: repo

- name: "APT: Update cache"
  ansible.builtin.apt:
    update_cache: true
  when: repo.changed

- name: Configure for Cloudstack Management
  ansible.builtin.include_tasks: "cloudstack-mgmt.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"]

- name: Configure for Cloudstack KVM Hypervisor
  ansible.builtin.include_tasks: "cloudstack-agent.yml"
  when: inventory_hostname in groups["cloudstack_kvm"]

# SystemVM is supposedly bundled with the official packages these days so no need to download and install.
#- name: Configure SystemVM Template
#  import_tasks: "cloudstack-systemvm.yml"
#  when: inventory_hostname in groups["cloudstack_mgmt"]
#  run_once: true

- name: Configure via CloudMonkey
  ansible.builtin.include_tasks: "cloudstack-api.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"]

- name: Provision Zones/Pods/Clusters
  ansible.builtin.include_tasks: "cloudstack-zone.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"] and cloudstack_zones is defined
  run_once: true

- name: Register KVM host with CloudStack zone/pod/cluster
  ansible.builtin.include_tasks: "cloudstack-zone-host.yml"
  when: inventory_hostname in groups["cloudstack_kvm"] and cloudstack_zone is defined

- name: Sync users/projects from LDAP
  ansible.builtin.include_tasks: "cloudstack-ldapsync.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"] and cloudstack_saml_enable
