---
- name: "APT: Install cloudstack repository for Debiazn-based systems"
  when: ansible_os_family == "Debian"
  run_once: true
  block:
  - name: "APT: see if we have a keyring"
    stat:
      path: /etc/apt/trusted.gpg.d/cloudstack.asc
    register: keyring_exists

  - name: "APT: fetch keyring"
    ansible.builtin.get_url:
      url: https://download.cloudstack.org/release.asc
      dest: /etc/apt/trusted.gpg.d/cloudstack.asc
      mode: "644"
    when: not keyring_exists.stat.exists
    register: keyring

  - name: "APT: Import Key"
    shell: "apt-key add /etc/apt/trusted.gpg.d/cloudstack.asc"
    when: keyring.changed

  - name: "APT: Install cloudstack repository"
    template:
      src: cloudstack.sources.debian.j2
      dest: /etc/apt/sources.list.d/cloudstack.sources
      owner: root
      mode: "644"
    register: repo

- name: "YUM: Install cloudstack repository"
  template:
    src: cloudstack.sources.el.j2
    dest: /etc/yum.repos.d/cloudstack.repo
    owner: root
    mode: "644"
  register: repo
  when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky"

- name: "Package: Update cache"
  ansible.builtin.package:
    update_cache: true
  when: repo.changed

- name: Configure for Cloudstack Management
  import_tasks: "cloudstack-mgmt.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"]

- name: Configure for Cloudstack KVM Hypervisor
  import_tasks: "cloudstack-agent.yml"
  when: inventory_hostname in groups["cloudstack_kvm"]

# SystemVM is supposedly bundled with the official packages these days so no need to download and install.
#- name: Configure SystemVM Template
#  import_tasks: "cloudstack-systemvm.yml"
#  when: inventory_hostname in groups["cloudstack_mgmt"]
#  run_once: true

- name: Configure via CloudMonkey
  import_tasks: "cloudstack-api.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"]

- name: Sync users/projects from LDAP
  import_tasks: "cloudstack-ldapsync.yml"
  when: inventory_hostname in groups["cloudstack_mgmt"] and cloudstack_saml_enable
